### ISSUE TITLE
TODO アプリの画面デザインを考える

### ISSUE THREAD

**Issue by yui666a** [style-arts-corp/obpr-sato-web#9]
# 概要

* 自分が使いやすいと思うTODOアプリの画面デザインを作ってください
* PC用アプリ or スマホ用アプリ or タブレットアプリ か最初に選択してください．
  * レスポンシブデザインを考えなくて大丈夫です

**ただし，難しすぎる・凝りすぎたデザインを考えたら，実装で困るのは自分なので，そこら辺の塩梅も考慮してください**

* 画面は２ページ以上使うようにしてください

# 期待する動作

- [ ] Figma など好きなデザインツールを使ってTODOアプリのデザインを考える
    - そこまで凝らなくても大丈夫！　「デザイン X%，プログラミング Y% の割合で頑張りたい」をそのままデザイン作成の頑張り度に反映させてください
    - 紙に手書きでもあり
- [ ] 画面が２ページ以上存在するデザインにすること

# 現状 (バグの場合)

スクショ or 動画 or 説明 を記入してください。

**Comment by moe310** [comment]
![Image](https://github.com/user-attachments/assets/91d2a782-3f51-48ea-81a1-113d22675eda)

とりあえずFigmaで作ってみました。
EDUプランで作成したので画像での共有になります。

**Comment by yui666a** [comment]
僕的にはめちゃくちゃよく出来てると思います！！
正直こんなにしっかりとしたものが出てくると思ってなかったです笑

**Comment by OdenCraftsman** [comment]
すごいです！！
無駄のないデザインで直感的に操作できそう！だと思いました！
以下山口（DXデザイン事業部）からのフィードバックです！

- 3段階チェックボックスの実装が難しそう（僕の知見不足かもです、調べたんですけど、muiではコンポーネントとしては存在しなかった？）
   - プルダウンとかの方が実装は楽だと思う
- 下の画面について
    - タイトルが上の方がUX高そう！（優先度はタイトルに対してつくものなので）
-  Doneの時に優先度の表示も変わると視認性が上がりそう！
　　- チェック状態に応じて、CSSを変えるの少し難しそう？な気もするから挑戦的な内容かも！

以上です！！
全体的にめちゃめちゃいいと思うので、引き続き頑張ってください！
開発でわからないことあったら、教えられます！
頑張ってーー！！！！

**Comment by yui666a** [comment]
@moe310 

エンジニア目線からすると、めちゃくちゃ良いデザインだと思います！
優先度を色の濃淡で表現するのとかもなるほどなぁと思いながら拝見しました

とは言え開発を行う前にいくつか確認と質問をさせてください！

1. 完了したタスクは表示され続ける想定ですか？
表示され続ける、消える、表示・非表示を切り替えるなどの選択肢があると思いますのでイメージを聞かせてください

2. ゴミ箱アイコンがクリックされたらタスクは即時削除されますか？
ToDoリスト(やることリスト)なのに簡単に触ってしまいそうな場所に配置してあるアイコンに当たるとタスクが削除されてしまうのは少し怖い気がしました。
削除できる場所を変更する or 確認モーダルを挟んで2段階で操作が必要にするなど様々な対策があると思います
もちろん強い意志があれば、現状のままで大丈夫です！

3. 2ページ目のタスク名の入力欄が上下の他の要素と横幅が揃っていないのは理由がありますか？
ここに対してはただの疑問です！

4. 優先度やステータスでフィルタリングしたタスクに表示が切り替わるタイミングは虫眼鏡アイコンを押した時ですか？
質問2の削除操作とは逆にこの検索は1回1回虫眼鏡アイコン押すの面倒くさいなと思った感じです。
(僕がただ面倒くさがりなだけです)

5. ステータスの変更はどのように操作しますか？

6. 質問5とも関連しますが、個別タスクのステータスを示すマルチチェックボックス(以下、セレクトボックスとします)は、html 標準のセレクトボックスを使用する想定ですか？
ステータスを表すためにセレクトボックスのデザインを3つ定義しているのはすごいいいと思います！
しかし web標準のセレクトボックスには3状態を指定することが難しいです(実際には checkbox indeterminateで簡単に実装はできますが、挙動が少しややこしい)
どのように実装する想定か軽く教えてくださいー！

7. 2ページ目の優先度選択エリアを囲うボーダーが角張ってますが想定通りですか？
他の要素は角を丸めていると思うのですがここだけ尖ってたので確認だけ

**Comment by moe310** [comment]
山口さん、相曽さん
フィードバックありがとうございます！
現在、出先でPCがないので返信が見にくいかもしれませんがご容赦ください。
以下、いただいたフィードバックに対する回答です。

@OdenCraftsman 
* 3段階チェックボックスの実装が難しそう（僕の知見不足かもです、調べたんですけど、muiではコンポーネントとしては存在しなかった？）
    * プルダウンとかの方が実装は楽だと思う
→ とりあえずデザイン案として吐き出したのですが、確かに難しそう... 操作はプルダウンでアイコンとして今のデザインを残す感じが妥当ですかね？
* 下の画面について
    * タイトルが上の方がUX高そう！（優先度はタイトルに対してつくものなので）
→ごもっともですね。この辺は脳みそが死んでました… 修正します！
* Doneの時に優先度の表示も変わると視認性が上がりそう！ 　　- チェック状態に応じて、CSSを変えるの少し難しそう？な気もするから挑戦的な内容かも！
→「チェック状態に応じて、CSSを変えるの少し難しそう」←この辺はやったことがあるはずなので頑張ります。doneでは優先度の彩度を落としたいですね。

@yui666a 
1. 「完了したタスク」はDoneの状態ですかね？Todo、doing、doneの3状態要求されていたので、残す(表示され続ける)イメージでした。 doneの表示・非表示を切り替えられるのはいい案ですね。余裕があれば切り替えも実装したいです。
2. ゴミ箱アイコンがクリックされてもタスクは即時削除されない方向で考えています。 確認モーダルを挟んで2段階で操作するイメージです。画面作るのを忘れていました🙇‍♀️
3. 2ページ目のタスク名の入力欄が上下の他の要素と横幅が揃っていないのには、特に深い理由はありませんが、read画面(画面1)と改行位置を揃えた時に、余白が気になったので縮ませてました。要素の幅を全て揃えた方がいいなら揃えます。結構フィーリングです。
4. 優先度やステータスでフィルタリングしたタスクに表示が切り替わるタイミングは虫眼鏡アイコンを押した時ですか？→そうです！
5. ステータスの変更はタップして変更するイメージ(todo→doing→done→todo...)でしたが、山口さんのフィードバックを受けて、プルダウンで変更しようかと考えています。(チェックボックスのアイコンタップでプルダウン→ステータス選択→選択したステータスに対応するアイコンが表示)
6. デザインを考えた時には状態を3つ用意してタップごとに連動したアイコンを表示する(web標準のセレクトボックスは使わない) イメージでしたが、技術的に実装可能かどうかは調査してませんでした...

**Comment by moe310** [comment]
いただいたフィードバックをもとにデザインを修正しました。


![Image](https://github.com/user-attachments/assets/05778595-5a2f-4a8c-abbb-875c1d8d0ff4)


修正点
① 画面2の優先度とタスク名の入力欄の位置を入れ替え、要素の横幅を揃えた。
　@yui666a 
　7. 要素の角は想定通りでした。ご指摘いただいてから、優先度とタスク名の入力欄の角は揃えた方がいいと考えなおし、両方角張らせています。ボタンと入力欄の差を感じさせるためにボタンの角は丸めています。
② Doneの時に優先度の彩度(HSLのS)を0に変更。
③ 確認モーダルを表示する際の画面デザインを追加。

**Comment by moe310** [comment]
③の確認モーダルの画面ですが、削除対象のタスクを表示する際に編集・削除のアイコンは非表示の方がいいでしょうか？

ご意見お聞かせください🙇‍♀️



![Image](https://github.com/user-attachments/assets/96ad0199-cf6a-4871-b297-872685cac61f)

**Comment by yui666a** [comment]
> ③の確認モーダルの画面ですが、削除対象のタスクを表示する際に編集・削除のアイコンは非表示の方がいいでしょうか？
> 
> ご意見お聞かせください🙇‍♀️
> 
> 
> 
> ![Image](https://github.com/user-attachments/assets/96ad0199-cf6a-4871-b297-872685cac61f)
> 
> 

@moe310 
僕はアイコンがない方ができることが明示的で分かりやすいと思います！
ただ共通コンポーネントとして開発しにくいなど思うならそのままでも大丈夫だと思いますー！

**Comment by pTheamtun** [comment]
パッと見てみやすいと思います
使いやすそう

適当すぎてごめんなさい🙇!!! 
このdesign好きです

**Comment by yui666a** [comment]
@moe310 
デザインはいい感じだと思いますー！
次のタスクに進んでもらっても大丈夫です！
